// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace myClient.Models
{
    /// <summary> Model factory for read-only models. </summary>
    public static partial class ExampleWebAPIModelFactory
    {
        /// <summary> Initializes a new instance of WeatherForecast. </summary>
        /// <param name="date"></param>
        /// <param name="temperatureC"></param>
        /// <param name="temperatureF"></param>
        /// <param name="summary"></param>
        /// <returns> A new <see cref="Models.WeatherForecast"/> instance for mocking. </returns>
        public static WeatherForecast WeatherForecast(DateTimeOffset? date = null, int? temperatureC = null, int? temperatureF = null, string summary = null)
        {
            return new WeatherForecast(date, temperatureC, temperatureF, summary);
        }
    }
}
