// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace myClient.Models
{
    /// <summary> The WeatherForecast. </summary>
    public partial class WeatherForecast
    {
        /// <summary> Initializes a new instance of WeatherForecast. </summary>
        internal WeatherForecast()
        {
        }

        /// <summary> Initializes a new instance of WeatherForecast. </summary>
        /// <param name="date"></param>
        /// <param name="temperatureC"></param>
        /// <param name="temperatureF"></param>
        /// <param name="summary"></param>
        internal WeatherForecast(DateTimeOffset? date, int? temperatureC, int? temperatureF, string summary)
        {
            Date = date;
            TemperatureC = temperatureC;
            TemperatureF = temperatureF;
            Summary = summary;
        }

        /// <summary> Gets the date. </summary>
        public DateTimeOffset? Date { get; }
        /// <summary> Gets the temperature c. </summary>
        public int? TemperatureC { get; }
        /// <summary> Gets the temperature f. </summary>
        public int? TemperatureF { get; }
        /// <summary> Gets the summary. </summary>
        public string Summary { get; }
    }
}
